FROM docker.pkg.github.com/geniuslinux/test-ent/dockerfile.base:latest

RUN apt install -y python3-pip automake device-tree-compiler
COPY --from=docker.pkg.github.com/geniuslinux/test-ent/dockerfile.base:latest /root/test/toto /root/test/
